version: '3.1'

services:
   mysql:
     image: mysql:5.6
     environment:
       MYSQL_ROOT_PASSWORD: yetiforce
     restart: always
     ports:
       - "3306:3306"
     command: mysqld --sql_mode="STRICT_TRANS_TABLE" --sql_mode="ONLY_FULL_GROUP_BY"  --character-set-server="utf8" --collation-server="utf8_unicode_ci" --max-allowed-packet="1073741824" --innodb_lock_wait_timeout="600"

     

   yetiforce:
     links:
       - mysql
     build: 5.0.0
     ports:
       - "8000:80"
     restart: always

